import { Data, IProductInput } from "@/types"
import { toSlug } from "./utils"

const products: IProductInput[] = [
    {
        name: "Nike mens slim-fit long-sleeve t-shirt",
        slug: toSlug("Nike mens slim-fit long-sleeve t-shirt"),
        category: "tshirt",
        images: ['/images/tshirt1.jpg', '/images/tshirt2.jpg'],
        tags: ['New Arrival'],
        isPublished: true,
        price: 49.99,
        listPrice: 0,
        brand: "Nike",
        avgRating: 4.5,
        numReviews: 7,
        ratingDistribution: [
            { rating: 1, count: 0 },
            { rating: 2, count: 0 },
            { rating: 3, count: 0 },
            { rating: 4, count: 2 },
            { rating: 5, count: 2 },
        ],
        numSales: 9,
        countInStock: 10,
        description: "Nike mens slim-fit long-sleeve t-shirt",
        colors: ['white', 'red', 'black'],
        sizes: ['S', 'M', 'L'],

        reviews: []
    },
    {
        name: "Adidas Running Shoes",
        slug: toSlug("Adidas Running Shoes"),
        category: "shoes",
        images: ['/images/shoes1.jpg', '/images/shoes2.jpg'],
        tags: ['Best Seller'],
        isPublished: true,
        price: 89.99,
        listPrice: 99.99,
        brand: "Adidas",
        avgRating: 4.8,
        numReviews: 15,
        ratingDistribution: [
            { rating: 1, count: 0 },
            { rating: 2, count: 1 },
            { rating: 3, count: 2 },
            { rating: 4, count: 5 },
            { rating: 5, count: 7 },
        ],
        numSales: 25,
        countInStock: 20,
        description: "High-quality running shoes for all terrains.",
        colors: ['blue', 'black', 'white'],
        sizes: ['8', '9', '10', '11'],

        reviews: []
    },
    {
        name: "Puma Sports Jacket",
        slug: toSlug("Puma Sports Jacket"),
        category: "jacket",
        images: ['/images/jacket1.jpg', '/images/jacket2.jpg'],
        tags: ['New Arrival'],
        isPublished: true,
        price: 59.99,
        listPrice: 79.99,
        brand: "Puma",
        avgRating: 4.2,
        numReviews: 10,
        ratingDistribution: [
            { rating: 1, count: 0 },
            { rating: 2, count: 1 },
            { rating: 3, count: 2 },
            { rating: 4, count: 4 },
            { rating: 5, count: 3 },
        ],
        numSales: 18,
        countInStock: 15,
        description: "Lightweight and comfortable sports jacket.",
        colors: ['red', 'black'],
        sizes: ['M', 'L', 'XL'],
        reviews: []
    },
    {
        name: "Ray-Ban Aviator Sunglasses",
        slug: toSlug("Ray-Ban Aviator Sunglasses"),
        category: "accessories",
        images: ['/images/sunglasses1.jpg', '/images/sunglasses2.jpg'],
        tags: ['Trending'],
        isPublished: true,
        price: 129.99,
        listPrice: 149.99,
        brand: "Ray-Ban",
        avgRating: 4.7,
        numReviews: 25,
        ratingDistribution: [
            { rating: 1, count: 0 },
            { rating: 2, count: 0 },
            { rating: 3, count: 3 },
            { rating: 4, count: 7 },
            { rating: 5, count: 15 },
        ],
        numSales: 30,
        countInStock: 12,
        description: "Classic Ray-Ban aviator sunglasses with UV protection.",
        colors: ['gold', 'black'],
        sizes: [],
        reviews: []
    },
    {
        name: "Apple AirPods Pro",
        slug: toSlug("Apple AirPods Pro"),
        category: "electronics",
        images: ['/images/airpods1.jpg', '/images/airpods2.jpg'],
        tags: ['Best Seller', 'Electronics'],
        isPublished: true,
        price: 199.99,
        listPrice: 249.99,
        brand: "Apple",
        avgRating: 4.9,
        numReviews: 50,
        ratingDistribution: [
            { rating: 1, count: 0 },
            { rating: 2, count: 1 },
            { rating: 3, count: 2 },
            { rating: 4, count: 10 },
            { rating: 5, count: 37 },
        ],
        numSales: 100,
        countInStock: 25,
        description: "Apple AirPods Pro with active noise cancellation and spatial audio.",
        colors: ['white'],
        sizes: [],
        reviews: []
    },
    {
        name: "Samsung Galaxy S21",
        slug: toSlug("Samsung Galaxy S21"),
        category: "electronics",
        images: ['/images/samsung1.jpg', '/images/samsung2.jpg'],
        tags: ['Best Seller', 'Electronics'],
        isPublished: true,
        price: 799.99,
        listPrice: 999.99,
        brand: "Samsung",
        avgRating: 4.6,
        numReviews: 40,
        ratingDistribution: [
            { rating: 1, count: 0 },
            { rating: 2, count: 2 },
            { rating: 3, count: 5 },
            { rating: 4, count: 15 },
            { rating: 5, count: 18 },
        ],
        numSales: 80,
        countInStock: 30,
        description: "Latest Samsung Galaxy S21 with high-resolution display.",
        colors: ['black', 'white', 'blue'],
        sizes: [],
        reviews: []
    },
    {
        name: "Sony WH-1000XM4 Headphones",
        slug: toSlug("Sony WH-1000XM4 Headphones"),
        category: "electronics",
        images: ['/images/headphones1.jpg', '/images/headphones2.jpg'],
        tags: ['Best Seller', 'Electronics'],
        isPublished: true,
        price: 349.99,
        listPrice: 399.99,
        brand: "Sony",
        avgRating: 4.8,
        numReviews: 30,
        ratingDistribution: [
            { rating: 1, count: 0 },
            { rating: 2, count: 1 },
            { rating: 3, count: 3 },
            { rating: 4, count: 10 },
            { rating: 5, count: 16 },
        ],
        numSales: 60,
        countInStock: 20,
        description: "Sony WH-1000XM4 wireless noise-canceling headphones.",
        colors: ['black', 'silver'],
        sizes: [],
        reviews: []
    },
    {
        name: "Dell XPS 13 Laptop",
        slug: toSlug("Dell XPS 13 Laptop"),
        category: "electronics",
        images: ['/images/laptop1.jpg', '/images/laptop2.jpg'],
        tags: ['Best Seller', 'Electronics'],
        isPublished: true,
        price: 999.99,
        listPrice: 1199.99,
        brand: "Dell",
        avgRating: 4.7,
        numReviews: 20,
        ratingDistribution: [
            { rating: 1, count: 0 },
            { rating: 2, count: 0 },
            { rating: 3, count: 2 },
            { rating: 4, count: 8 },
            { rating: 5, count: 10 },
        ],
        numSales: 50,
        countInStock: 15,
        description: "Dell XPS 13 laptop with high-resolution display and powerful performance.",
        colors: ['silver', 'black'],
        sizes: [],
        reviews: []
    },
    {
        name: "HP Spectre x360",
        slug: toSlug("HP Spectre x360"),
        category: "electronics",
        images: ['/images/hp1.jpg', '/images/hp2.jpg'],
        tags: ['Best Seller', 'Electronics'],
        isPublished: true,
        price: 1299.99,
        listPrice: 1499.99,
        brand: "HP",
        avgRating: 4.5,
        numReviews: 25,
        ratingDistribution: [
            { rating: 1, count: 0 },
            { rating: 2, count: 0 },
            { rating: 3, count: 3 },
            { rating: 4, count: 10 },
            { rating: 5, count: 12 },
        ],
        numSales: 40,
        countInStock: 10,
        description: "HP Spectre x360 convertible laptop with touchscreen.",
        colors: ['silver', 'black'],
        sizes: [],
        reviews: []
    },
    {
        name: "MacBook Pro 16-inch",
        slug: toSlug("MacBook Pro 16-inch"),
        category: "electronics",
        images: ['/images/macbook1.jpg', '/images/macbook2.jpg'],
        tags: ['Best Seller', 'Electronics'],
        isPublished: true,
        price: 2399.99,
        listPrice: 2599.99,
        brand: "Apple",
        avgRating: 4.9,
        numReviews: 15,
        ratingDistribution: [
            { rating: 1, count: 0 },
            { rating: 2, count: 0 },
            { rating: 3, count: 1 },
            { rating: 4, count: 5 },
            { rating: 5, count: 9 },
        ],
        numSales: 20,
        countInStock: 8,
        description: "Apple MacBook Pro with M1 chip and Retina display.",
        colors: ['silver', 'space gray'],
        sizes: [],
        reviews: []
    },
    {
        name: "ASUS ROG Zephyrus G14",
        slug: toSlug("ASUS ROG Zephyrus G14"),
        category: "electronics",
        images: ['/images/asus1.jpg', '/images/asus2.jpg'],
        tags: ['Best Seller', 'Electronics'],
        isPublished: true,
        price: 1499.99,
        listPrice: 1699.99,
        brand: "ASUS",
        avgRating: 4.6,
        numReviews: 18,
        ratingDistribution: [
            { rating: 1, count: 0 },
            { rating: 2, count: 0 },
            { rating: 3, count: 2 },
            { rating: 4, count: 8 },
            { rating: 5, count: 8 },
        ],
        numSales: 35,
        countInStock: 12,
        description: "ASUS ROG Zephyrus G14 gaming laptop with powerful performance.",
        colors: ['white', 'black'],
        sizes: [],
        reviews: []
    },
    {
        name: "Lenovo ThinkPad X1 Carbon",
        slug: toSlug("Lenovo ThinkPad X1 Carbon"),
        category: "electronics",
        images: ['/images/lenovo1.jpg', '/images/lenovo2.jpg'],
        tags: ['Best Seller', 'Electronics'],
        isPublished: true,
        price: 1399.99,
        listPrice: 1599.99,
        brand: "Lenovo",
        avgRating: 4.4,
        numReviews: 22,
        ratingDistribution: [
            { rating: 1, count: 0 },
            { rating: 2, count: 0 },
            { rating: 3, count: 3 },
            { rating: 4, count: 10 },
            { rating: 5, count: 9 },
        ],
        numSales: 28,
        countInStock: 10,
        description: "Lenovo ThinkPad X1 Carbon with high-performance features.",
        colors: ['black'],
        sizes: [],
        reviews: []
    },
    {
        name: "Microsoft Surface Laptop 4",
        slug: toSlug("Microsoft Surface Laptop 4"),
        category: "electronics",
        images: ['/images/surface1.jpg', '/images/surface2.jpg'],
        tags: ['Best Seller', 'Electronics'],
        isPublished: true,
        price: 1299.99,
        listPrice: 1399.99,
        brand: "Microsoft",
        avgRating: 4.5,
        numReviews: 20,
        ratingDistribution: [
            { rating: 1, count: 0 },
            { rating: 2, count: 0 },
            { rating: 3, count: 2 },
            { rating: 4, count: 8 },
            { rating: 5, count: 10 },
        ],
        numSales: 30,
        countInStock: 15,
        description: "Microsoft Surface Laptop 4 with high-resolution display.",
        colors: ['silver', 'black'],
        sizes: [],
        reviews: []
    },
    {
        name: "Google Pixel 6",
        slug: toSlug("Google Pixel 6"),
        category: "electronics",
        images: ['/images/pixel1.jpg', '/images/pixel2.jpg'],
        tags: ['Best Seller', 'Electronics'],
        isPublished: true,
        price: 599.99,
        listPrice: 699.99,
        brand: "Google",
        avgRating: 4.7,
        numReviews: 25,
        ratingDistribution: [
            { rating: 1, count: 0 },
            { rating: 2, count: 0 },
            { rating: 3, count: 3 },
            { rating: 4, count: 10 },
            { rating: 5, count: 12 },
        ],
        numSales: 45,
        countInStock: 20,
        description: "Google Pixel 6 with advanced camera features.",
        colors: ['black', 'white'],
        sizes: [],
        reviews: []
    },
    {
        name: "OnePlus 9",
        slug: toSlug("OnePlus 9"),
        category: "electronics",
        images: ['/images/oneplus1.jpg', '/images/oneplus2.jpg'],
        tags: ['Best Seller', 'Electronics'],
        isPublished: true,
        price: 699.99,
        listPrice: 799.99,
        brand: "OnePlus",
        avgRating: 4.6,
        numReviews: 30,
        ratingDistribution: [
            { rating: 1, count: 0 },
            { rating: 2, count: 0 },
            { rating: 3, count: 2 },
            { rating: 4, count: 12 },
            { rating: 5, count: 16 },
        ],
        numSales: 50,
        countInStock: 25,
        description: "OnePlus 9 with high-performance features.",
        colors: ['black', 'blue'],
        sizes: [],
        reviews: []
    },
    {
        name: "Xiaomi Mi 11",
        slug: toSlug("Xiaomi Mi 11"),
        category: "electronics",
        images: ['/images/xiaomi1.jpg', '/images/xiaomi2.jpg'],
        tags: ['Best Seller', 'Electronics'],
        isPublished: true,
        price: 749.99,
        listPrice: 849.99,
        brand: "Xiaomi",
        avgRating: 4.5,
        numReviews: 28,
        ratingDistribution: [
            { rating: 1, count: 0 },
            { rating: 2, count: 1 },
            { rating: 3, count: 5 },
            { rating: 4, count: 10 },
            { rating: 5, count: 12 },
        ],
        numSales: 55,
        countInStock: 18,
        description: "Xiaomi Mi 11 with advanced camera and performance.",
        colors: ['black', 'white'],
        sizes: [],
        reviews: []
    },
    {
        name: "Oculus Quest 2",
        slug: toSlug("Oculus Quest 2"),
        category: "electronics",
        images: ['/images/oculus1.jpg', '/images/oculus2.jpg'],
        tags: ['Best Seller', 'Electronics'],
        isPublished: true,
        price: 299.99,
        listPrice: 399.99,
        brand: "Oculus",
        avgRating: 4.8,
        numReviews: 35,
        ratingDistribution: [
            { rating: 1, count: 0 },
            { rating: 2, count: 0 },
            { rating: 3, count: 3 },
            { rating: 4, count: 12 },
            { rating: 5, count: 20 },
        ],
        numSales: 70,
        countInStock: 40,
        description: "Oculus Quest 2 VR headset with advanced features.",
        colors: ['white'],
        sizes: [],
        reviews: []
    },
    {
        name: "GoPro HERO9 Black",
        slug: toSlug("GoPro HERO9 Black"),
        category: "electronics",
        images: ['/images/gopro1.jpg', '/images/gopro2.jpg'],
        tags: ['Best Seller', 'Electronics'],
        isPublished: true,
        price: 399.99,
        listPrice: 499.99,
        brand: "GoPro",
        avgRating: 4.7,
        numReviews: 22,
        ratingDistribution: [
            { rating: 1, count: 0 },
            { rating: 2, count: 0 },
            { rating: 3, count: 2 },
            { rating: 4, count: 10 },
            { rating: 5, count: 10 },
        ],
        numSales: 60,
        countInStock: 30,
        description: "GoPro HERO9 Black with advanced camera features.",
        colors: ['black'],
        sizes: [],
        reviews: []
    },
    {
        name: "DJI Mavic Air 2",
        slug: toSlug("DJI Mavic Air 2"),
        category: "electronics",
        images: ['/images/dji1.jpg', '/images/dji2.jpg'],
        tags: ['Best Seller', 'Electronics'],
        isPublished: true,
        price: 799.99,
        listPrice: 899.99,
        brand: "DJI",
        avgRating: 4.9,
        numReviews: 18,
        ratingDistribution: [
            { rating: 1, count: 0 },
            { rating: 2, count: 0 },
            { rating: 3, count: 1 },
            { rating: 4, count: 7 },
            { rating: 5, count: 10 },
        ],
        numSales: 40,
        countInStock: 25,
        description: "DJI Mavic Air 2 drone with advanced features.",
        colors: ['white', 'black'],
        sizes: [],
        reviews: []
    },
    {
        name: "Sony WH-1000XM4",
        slug: toSlug("Sony WH-1000XM4"),
        category: "electronics",
        images: ['/images/sony1.jpg', '/images/sony2.jpg'],
        tags: ['Best Seller', 'Electronics'],
        isPublished: true,
        price: 1299.99,
        listPrice: 1499.99,
        brand: "Sony",
        avgRating: 4.6,
        numReviews: 25,
        ratingDistribution: [
            { rating: 1, count: 0 },
            { rating: 2, count: 0 },
            { rating: 3, count: 2 },
            { rating: 4, count: 8 },
            { rating: 5, count: 12 },
        ],
        numSales: 50,
        countInStock: 20,
        description: "Sony WH-1000XM4 wireless earbuds with advanced noise cancellation.",
        colors: ['black', 'white'],
        sizes: [],
        reviews: []
    },
    {
        name: "Bose QuietComfort 35 II",
        slug: toSlug("Bose QuietComfort 35 II"),
        category: "electronics",
        images: ['/images/bose1.jpg', '/images/bose2.jpg'],
        tags: ['Best Seller', 'Electronics'],
        isPublished: true,
        price: 299.99,
        listPrice: 349.99,
        brand: "Bose",
        avgRating: 4.8,
        numReviews: 30,
        ratingDistribution: [
            { rating: 1, count: 0 },
            { rating: 2, count: 0 },
            { rating: 3, count: 3 },
            { rating: 4, count: 12 },
            { rating: 5, count: 15 },
        ],
        numSales: 60,
        countInStock: 25,
        description: "Bose QuietComfort 35 II wireless headphones with noise cancellation.",
        colors: ['black', 'silver'],
        sizes: [],
        reviews: []
    },
    {
        name: "Fitbit Charge 4",
        slug: toSlug("Fitbit Charge 4"),
        category: "electronics",
        images: ['/images/fitbit1.jpg', '/images/fitbit2.jpg'],
        tags: ['Best Seller', 'Electronics'],
        isPublished: true,
        price: 149.99,
        listPrice: 199.99,
        brand: "Fitbit",
        avgRating: 4.5,
        numReviews: 20,
        ratingDistribution: [
            { rating: 1, count: 0 },
            { rating: 2, count: 0 },
            { rating: 3, count: 2 },
            { rating: 4, count: 8 },
            { rating: 5, count: 10 },
        ],
        numSales: 35,
        countInStock: 15,
        description: "Fitbit Charge 4 fitness tracker with GPS.",
        colors: ['black', 'blue'],
        sizes: [],
        reviews: []
    },
    {
        name: "Garmin Forerunner 245",
        slug: toSlug("Garmin Forerunner 245"),
        category: "electronics",
        images: ['/images/garmin1.jpg', '/images/garmin2.jpg'],
        tags: ['Best Seller', 'Electronics'],
        isPublished: true,
        price: 299.99,
        listPrice: 349.99,
        brand: "Garmin",
        avgRating: 4.7,
        numReviews: 25,
        ratingDistribution: [
            { rating: 1, count: 0 },
            { rating: 2, count: 0 },
            { rating: 3, count: 3 },
            { rating: 4, count: 10 },
            { rating: 5, count: 12 },
        ],
        numSales: 50,
        countInStock: 20,
        description: "Garmin Forerunner 245 GPS running watch.",
        colors: ['black', 'red'],
        sizes: [],
        reviews: []
    },
    {
        name: "Samsung Galaxy Watch 3",
        slug: toSlug("Samsung Galaxy Watch 3"),
        category: "electronics",
        images: ['/images/samsung-watch1.jpg', '/images/samsung-watch2.jpg'],
        tags: ['Best Seller', 'Electronics'],
        isPublished: true,
        price: 399.99,
        listPrice: 449.99,
        brand: "Samsung",
        avgRating: 4.6,
        numReviews: 30,
        ratingDistribution: [
            { rating: 1, count: 0 },
            { rating: 2, count: 0 },
            { rating: 3, count: 3 },
            { rating: 4, count: 12 },
            { rating: 5, count: 15 },
        ],
        numSales: 60,
        countInStock: 25,
        description: "Samsung Galaxy Watch 3 with advanced health features.",
        colors: ['black', 'silver'],
        sizes: [],
        reviews: []
    }

]

const data: Data = {
    products,
    headerMenus: [
        {
            name: "Today's Deals",
            href: '/search?tag=today-deals',
        },
        {
            name: "New Arrivals",
            href: '/search?tag=new-arrivals',
        },
        {
            name: "Featured Products",
            href: '/search?tag=featured',
        },
        {
            name: "Best Sellers",
            href: '/search?tag=best-seller',
        },
        {
            name: "Browsing History",
            href: '/#browsing-history',
        },
        {
            name: "Customer Service",
            href: '/page/customer-service',
        },
        {
            name: "About Us",
            href: '/page/about-us',
        },
        {
            name: "Help",
            href: '/page/help',
        }
    ],

    carousels: [
        {
            title: "Most Popular Products for sale",
            buttonCaption: "Shop Now",
            image: "/images/banners1.jpg",
            url: "/search?tag=popular",
            isPublished: true,
        },
        {
            title: "Best Sellet in tshirt",
            buttonCaption: "Shop Now",
            image: "/images/banners2.jpg",
            url: "/search?tag=tshirt",
            isPublished: true,
        },
        {
            title: "Best Deals on Wrist Watches",
            buttonCaption: "Shop Now",
            image: "/images/banners3.jpg",
            url: "/search?tag=wrist-watch",
            isPublished: true,
        }
    ],
}

export default data